# Artificial Neural Network

### Importing the libraries

In [14]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [15]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [16]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [17]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [18]:
y #dependent variable

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

### Splitting the dataset into the Training set and Test set

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) #to avoid diffrent random split we keep it to 0

## Part 2 - Building the ANN

### Initializing the ANN

In [20]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [21]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [22]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [23]:
#clssifciation with only 2 categories to predict in the end like yes or no (we have to use sigmoid activation function)
#clssifciation with more than 2 categories to predict in the end (we have to use soft max activation function)
# regression means predicting continous real number as final (no activation function)

ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [24]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [25]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 3ms/step - loss: 89594.3047
Epoch 2/100
240/240 [==============================] - 1s 3ms/step - loss: 1040.5588
Epoch 3/100
240/240 [==============================] - 1s 3ms/step - loss: 757.7369
Epoch 4/100
240/240 [==============================] - 1s 2ms/step - loss: 729.0685
Epoch 5/100
240/240 [==============================] - 1s 2ms/step - loss: 696.2803
Epoch 6/100
240/240 [==============================] - 1s 2ms/step - loss: 658.9984
Epoch 7/100
240/240 [==============================] - 1s 2ms/step - loss: 619.5907
Epoch 8/100
240/240 [==============================] - 1s 2ms/step - loss: 577.4346
Epoch 9/100
240/240 [==============================] - 1s 2ms/step - loss: 533.7373
Epoch 10/100
240/240 [==============================] - 1s 2ms/step - loss: 489.5844
Epoch 11/100
240/240 [==============================] - 1s 2ms/step - loss: 445.1344
Epoch 12/100
240/240 [==============================] - 1s 2ms/step - l

In [27]:
print(ann.predict(X_test))

60/60 [==============================] - 0s 2ms/step
[[430.65]
 [461.61]
 [465.07]
 ...
 [472.34]
 [439.16]
 [458.35]]


### Predicting the results of the Test set

In [26]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)# precision=2 - two decimals after comma
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[430.65 431.23]
 [461.61 460.01]
 [465.07 461.14]
 ...
 [472.34 473.26]
 [439.16 438.  ]
 [458.35 463.28]]
